spring:
  application:
    name: soccer-management-system
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

football-data:
  base-url: https://api.football-data.org/v4
  api-token: ffa4e22865b34b5396c8da9fd68bb360

api-football:
  base-url: https://v3.football.api-sports.io
  api-key: eca77528b9ca23928a83efc20e3c0b21

springdoc:
  swagger-ui:
    path: /swagger-ui.html
