spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/soccerdb
    username: soccer
    password: soccer
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
